rules = [
  RemoveUnused
  OrganizeImports
]

# Only remove unused imports, leave defs/vals intact
RemoveUnused.keepLocalImports = false       # remove unused local imports
RemoveUnused.keepPrivateMembers = true      # keep all private defs/vals
RemoveUnused.keepPublicMembers = true       # keep all public defs/vals

# Organize imports
OrganizeImports.sortImports = true
OrganizeImports.groups = [
  "java.",
  "javax.",
  "scala.",
  "cats.",
  "com.",
  "org."
]